version: '2'
services:

  restaurantdb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: restaurant

  adminer:
    image: adminer
    restart: always
    ports:
      - "18080:8080"